spring.application.name=dishcraft

spring.data.mongodb.uri=mongodb+srv://sasankadilum372_db_user:yvaBZbvQBm8VRwUs@cluster0.wpmonyf.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=dishcraft_db

spring.security.user.name=admin
spring.security.user.password=admin

jwt.secret=bXktc3VwZXItc2VjdXJlLTI1Ni1iaXQtc2VjcmV0LWZvci1qd3QtdGVzdA==

jwt.expiration=86400000 # 24 hours

server.port=8080

